name: safe_filename
description: Dart package to strip reserved characters from a filename (beta)
version: 0.0.1
homepage: https://github.com/2n-1/safe_filename

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
